title:             Clean Blog
email:             rahulpadmaraju16@gmail.com
description:       A Blog Theme by Start Bootstrap
author:            Rahul
baseurl:           "/blogs/"
url:               "https://lrahull.github.io/"

# Social Profiles
twitter_username:  lRahul1l
github_username:   lRAHULl


# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
